# Change these first
owner: mukherjeedebayan # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: DM Main (debayanmukherjee.com)
    url: https://debayanmukherjee.com
    maxResponseTime: 3000
  - name: DM Store (store.debayanmukherjee.com)
    url: https://store.debayanmukherjee.com
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.debayanmukherjee.com
  #baseUrl: /uptime-monitor
  logoUrl: https://rstr.in/debayanmukherjee/dm-store-assets/Svo08SLpavZ
  name: DM Status
  introTitle: "Debayan Mukherjee Infrastructure Status Page"
  introMessage: This is a status page displaying **real-time** status data of all our services
  navbar:
    - title: Contact
      href: https://store.debayanmukherjee.com/contact/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

name: Uptime CI
on:
  schedule:
    - cron: "*/1 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
